log:
  path: "/Users/csohb/GolandProjects/xbrother/bin/log"
  level: "debug"
  name: "xbrother"
db:
  dsn: "dkmk:DKMK12!@tcp(127.0.0.1:3306)/dkmk?charset=utf8mb4&parseTime=True&loc=Local"
  max_idle: 10
  max_conn: 20
web:
  base_url: "http://localhost:6682"
  app: "index.template.html"
  public_path: "/Users/csohb/GolandProjects/xbrother/web"
server:
  listen: ":6682"